# Node.js image
FROM node:15.3.0-alpine3.10
#Change working directory
WORKDIR /usr/src/app
#Install app dependecies
COPY package*.json /.
RUN npm install
#Bundle app source
COPY *.js .
#Expose port
EXPOSE 8080
#Start server
CMD ["node", "index.js"]

